# ---------------------------------------------------------------------------- #
#               VARIABLES                                                      #
# ---------------------------------------------------------------------------- #
ENV_NAME		:=	myenv
MY_PACKAGES		:=	mypackages
PYTHON_VERSION	:=	3.12
ACTIVATE_ENV	:=	conda run -n $(ENV_NAME)
